---
title: "R Notebook"
output: html_notebook
---
```{r}
library(stringr)
library(dplyr)
library(tidyr)
library(tidytext)
library(readr)
library(stringi)
library(textclean)
library(ggplot2)
library(scales)
library(plotly)
library(htmlwidgets)
```


```{r import_csv}
harmony_events <- read_csv("final.csv")
# Each event has the number of individuals and groups involved
```

```{r harmony_stats}
# Events involving only individuals
h_individuals <- harmony_events %>% filter(Individual >= 1, Group == 0) %>% mutate(total = Individual + Group) %>% mutate(Characters = "Individuals")

# Events involving individuals and groups
h_individual_and_group <- harmony_events %>% filter(Individual >= 1, Group >= 1) %>% mutate(total = Individual + Group) %>% mutate(Characters = "Individuals and Groups")

# Events involving only groups
h_groups <- harmony_events %>% filter(Individual == 0, Group >= 1) %>% mutate(total = Individual + Group) %>% mutate (Characters = "Groups")
```


```{r}
combined_table <- bind_rows(h_individuals, h_individual_and_group, h_groups) %>% group_by(Characters)
comparison <- ggplot(data = combined_table, aes(x = Characters, y = total, fill = Characters)) + geom_bar(stat="identity")
comparison
```

